### ISSUE TITLE
请问大佬政策数据如何保存至mongodb

### ISSUE THREAD

**Issue by chairmenfrog** [JinhuaSu/Policy_crawler#1]
pipeline的process_item用的是drop集合,自己调试修改时也没有提示create或者insert信息.每次访问似乎都只是保存在本地

**Comment by JinhuaSu** [comment]
我在本机调试，一般爬三页，然后丢服务器上跑，所以一开始drop只是为了删除调试时可能出现的错误数据列。我开发环境和运行环境都是ubuntu18配置的mongodb，用的是默认端口，python和mongodb交互用的是pymongo，你可以先尝试pymongo是否可以正常对操作mongodb。

**Comment by chairmenfrog** [comment]
查了好久SOF没效果,发现是mongo_uri和mongo_db变量的问题,自己clone的工程client参数必须直接使用字符串,不能放变量.

**Comment by chairmenfrog** [comment]
补充：是atlas云服务用户设置的问题，我连接用户设置的是AnyDbAdmin，添加readwriteAny权限就能操作了，可以使用srv形式的mongo_uri，mongo_db变量
